### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by vikram9494** [SubhamTyagi/loco-answers#162]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Intent.clone()' on a null object reference
	at ai.loko.hk.ui.ocr.MediaProjectionHelper.getMediaProjection(MediaProjectionHelper.java:56)
	at ai.loko.hk.ui.ocr.Screenshotter.takeScreenshot(Screenshotter.java:90)
	at ai.loko.hk.ui.services.OCRFloating.captureScreenshot(OCRFloating.java:233)
	at ai.loko.hk.ui.services.OCRFloating.access$400(OCRFloating.java:77)
	at ai.loko.hk.ui.services.OCRFloating$2.onClick(OCRFloating.java:223)
	at android.view.View.performClick(View.java:5716)
	at android.widget.TextView.performClick(TextView.java:10926)
	at android.view.View$PerformClick.run(View.java:22596)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
-----------------

Device Information

DEVICE.ID : 8c2837a902d347a2
USER.ID : 
APP.VERSION : 19
LAUNCHER.APP : com.sec.android.app.launcher
TIMEZONE : Asia/Kolkata
VERSION.RELEASE : 6.0.1
VERSION.INCREMENTAL : J500FXXU1BRC1
VERSION.SDK.NUMBER : 23
BOARD : MSM8916
BOOTLOADER : J500FXXU1BRC1
BRAND : samsung
CPU_ABI : armeabi-v7a
CPU_ABI2 : armeabi
DISPLAY : MMB29M.J500FXXU1BRC1
FINGERPRINT : samsung/j5ltexx/j5lte:6.0.1/MMB29M/J500FXXU1BRC1:user/release-keys
HARDWARE : qcom
HOST : SWDG4705
ID : MMB29M
MANUFACTURER : samsung
MODEL : SM-J500F
PRODUCT : j5ltexx
SERIAL : 5afbe46d
TAGS : release-keys
TIME : 1521180535000
TYPE : user
UNKNOWN : unknown
USER : dpi

**Comment by Rishav-G** [comment]
It just happens sometimes.
I dont think it is much of a problem
Happened with me almost 4-5 times only

**Comment by vikram9494** [comment]
before loco i used it did works to me
