### ISSUE TITLE
Loko hack ocr

### ISSUE THREAD

**Issue by deepakkumarraj2704** [SubhamTyagi/loco-answers#166]
Hi sir ocr thick se kaam nhi karta me jab ocr start krta hu tab app stop ho jaata he plz is bugs ko next update me kr dena or loko hack baar baar remove ho jaata he phir se start karna padta plz solve kr dena or thanks for giving this app for free

**Comment by Rishav-G** [comment]
2.0 beta 2 me sahi ho gya h crash

**Comment by royalchauhan** [comment]
Rishav-G if you could upload the app on dropbox , Google drive or anywhere else please do so and provide the 2.0 beta 2 to us.

**Comment by Rishav-G** [comment]
I can but not without the consent of maker.
@subhamtyagi

**Comment by royalchauhan** [comment]
Yes you may ask shubam sir but if he allows to do so please do it.

**Comment by pankajksu** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ai.loko.hk.ui.answers.Engine.getA1()' on a null object reference
	at ai.loko.hk.ui.services.OCRFloating$Update.onPostExecute(OCRFloating.java:382)
	at ai.loko.hk.ui.services.OCRFloating$Update.onPostExecute(OCRFloating.java:373)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)

**Comment by pankajksu** [comment]
Solve this. Plssssssss

**Comment by pankajksu** [comment]
App mye bohut sare bugs hai. Plssssssss sir solve this. Khas karke OCR ko solve kijiye. This is requested sir.

**Comment by SubhamTyagi** [comment]
New Beta update is available for download
