### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Rishav-G** [SubhamTyagi/loco-answers#173]
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dindia%2527s%2B1st%2Bfeminist%2Bpublishing%2Bhouse%2527s%2Bfounders%2Bwere%2Bjointly%2Bawarded%2B__%2Bin%2B2011.%26num%3D30&q=EhAkBQIFQ46VZ1p1KxchTxMTGKHQzN0FIhkA8aeDSz2he7_c0FOLvjJ8rUFUeaGzAKcGMgFy
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:776)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:773)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295)
	at ai.loko.hk.ui.answers.Engine.googleSearch(Engine.java:213)
	at ai.loko.hk.ui.answers.Engine.search(Engine.java:76)
	at ai.loko.hk.ui.Accessibility$Update.doInBackground(Accessibility.java:448)
	at ai.loko.hk.ui.Accessibility$Update.doInBackground(Accessibility.java:413)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
-----------------

Device Information

DEVICE.ID : dcccfc6271310d63
USER.ID : 
APP.VERSION : 19
LAUNCHER.APP : com.miui.home
TIMEZONE : Asia/Calcutta
VERSION.RELEASE : 7.0
VERSION.INCREMENTAL : V9.6.3.0.NCFMIFD
VERSION.SDK.NUMBER : 24
BOARD : msm8953
BOOTLOADER : unknown
BRAND : xiaomi
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : AL1512-mido-build-20180918164722
FINGERPRINT : xiaomi/mido/mido:7.0/NRD90M/V9.6.3.0.NCFMIFD:user/release-keys
HARDWARE : qcom
HOST : mi-server
ID : NRD90M
MANUFACTURER : Xiaomi
MODEL : Redmi Note 4
PRODUCT : mido
SERIAL : 47c262a50204
TAGS : release-keys
TIME : 1537264040000
TYPE : user
UNKNOWN : unknown
USER : builder

**Comment by SubhamTyagi** [comment]
IP BLOCKED
