### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Dpereiraa** [SubhamTyagi/loco-answers#231]
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://www.google.com/searchone+japanese+alcoholic+drinks+made+rice%2C+yams+wear+or+brown+sugar++chubai+wikipedia+&num=2
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:776)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295)
	at ai.loko.hk.ui.answers.WikiSearch.run(WikiSearch.java:73)
-----------------

**Comment by Dpereiraa** [comment]
This app used to work before now it's not working my net is fast but it just doesn't give answers my device is motog3
