### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Akashchakale** [SubhamTyagi/loco-answers#247]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Data file not found at /storage/emulated/0/tesseract/tessdata/eng.traineddata
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:339)
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:303)
	at ai.loko.hk.ui.ocr.TesseractImageTextReader.getTextFromBitmap(TesseractImageTextReader.java:46)
	at ai.loko.hk.ui.services.OCRFloating$TakeScreenShot.doInBackground(OCRFloating.java:336)
	at ai.loko.hk.ui.services.OCRFloating$TakeScreenShot.doInBackground(OCRFloating.java:281)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
-----------------

Device Information

DEVICE.ID : 318d92b54f3f3b06
USER.ID : 
APP.VERSION : 23
LAUNCHER.APP : com.dlto.atom.launcher
TIMEZONE : Asia/Calcutta
VERSION.RELEASE : 6.0.1
VERSION.INCREMENTAL : eng.root.20180806.181819
VERSION.SDK.NUMBER : 23
BOARD : QC_Reference_Phone
BOOTLOADER : unknown
BRAND : OPPO
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : CPH1701EX_11_A.34_180806
FINGERPRINT : OPPO/CPH1701/CPH1701:6.0.1/MMB29M/1525659652:user/release-keys
HARDWARE : qcom
HOST : WX-31-217
ID : MMB29M
MANUFACTURER : OPPO
MODEL : CPH1701
PRODUCT : CPH1701
SERIAL : 1073ce45
TAGS : release-keys
TIME : 1533550859000
TYPE : user
UNKNOWN : unknown
USER : root

**Comment by chetan1728** [comment]
Yes bro it is crashing more time many wrong answers

**Comment by pankajksu** [comment]
App crash Kar Raha hai
