### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by deviladitya** [SubhamTyagi/loco-answers#262]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: Data file not found at /storage/emulated/0/tesseract/tessdata/eng.traineddata
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:339)
	at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:303)
	at ai.loko.hk.ui.ocr.TesseractImageTextReader.getTextFromBitmap(TesseractImageTextReader.java:46)
	at ai.loko.hk.ui.services.OCRFloating$TakeScreenShot.doInBackground(OCRFloating.java:336)
	at ai.loko.hk.ui.services.OCRFloating$TakeScreenShot.doInBackground(OCRFloating.java:281)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
-----------------

Device Information

DEVICE.ID : d5a5adc1a50ad5c6
USER.ID : 
APP.VERSION : 23
LAUNCHER.APP : com.android.launcher3
TIMEZONE : Asia/Kolkata
VERSION.RELEASE : 7.0
VERSION.INCREMENTAL : 21
VERSION.SDK.NUMBER : 24
BOARD : msm8937
BOOTLOADER : 0xB825
BRAND : motorola
CPU_ABI : armeabi-v7a
CPU_ABI2 : armeabi
DISPLAY : NPPS25.137-93-14
FINGERPRINT : motorola/cedric/cedric:7.0/NPPS25.137-93-14/21:user/release-keys
HARDWARE : qcom
HOST : ilclbld69
ID : NPPS25.137-93-14
MANUFACTURER : motorola
MODEL : Moto G (5)
PRODUCT : cedric
SERIAL : ZY3222ZDM8
TAGS : release-keys
TIME : 1529407439000
TYPE : user
UNKNOWN : unknown
USER : hudsoncm

**Comment by deviladitya** [comment]
Sir OCR is not working on HQ Trivia please help!!

**Comment by SubhamTyagi** [comment]
If you are getting above error.
Then either download Tesseract data for English language
 or use Google vision

**Comment by deviladitya** [comment]
I downloaded tesseract data but showing same problem.
