### ISSUE TITLE
App crashing too frequently

### ISSUE THREAD

**Issue by shinron001** [SubhamTyagi/loco-answers#289]
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
	at java.util.ArrayList.get(ArrayList.java:313)
	at ai.loko.hk.ui.answers.WikiSearch.run(WikiSearch.java:73)

**Comment by Anspri143** [comment]
Yeah bro... Now a days the app is crashing frequently .. Dont know why.. Previously it was working superb in my phone but it dont
