### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by shibapradhan** [SubhamTyagi/loco-answers#415]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Intent.clone()' on a null object reference
	at ai.loko.hk.ui.ocr.MediaProjectionHelper.getMediaProjection(MediaProjectionHelper.java:56)
	at ai.loko.hk.ui.ocr.Screenshotter.takeScreenshot(Screenshotter.java:92)
	at ai.loko.hk.ui.services.OCRFloating$2.onClick(OCRFloating.java:181)
	at android.view.View.performClick(View.java:5212)
	at android.view.View$PerformClick.run(View.java:21214)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
-----------------

Device Information

USER.ID : 
APP.VERSION : 28
LAUNCHER.APP : com.bbk.launcher2
TIMEZONE : Asia/Calcutta
VERSION.RELEASE : 6.0.1
VERSION.INCREMENTAL : eng.compiler.20190306.175921
VERSION.SDK.NUMBER : 23
BRAND : vivo
CPU_ABI : armeabi-v7a
CPU_ABI2 : armeabi
MANUFACTURER : vivo
MODEL : vivo 1603
PRODUCT : 1603

**Comment by shibapradhan** [comment]
Bhai ye app vivo me Support nehi karega kya.....

**Comment by shibapradhan** [comment]
Subham bhai rply do....

**Comment by SubhamTyagi** [comment]
working in oppo,vivo,realme

it seems that your trivia app using secure flag to prevent taking a screenshots

**Comment by shibapradhan** [comment]
On Jul 31, 2019 11:06 AM, "Shubham" <notifications@github.com> wrote:

working in oppo,vivo,realme

it seems that your trivia app using secure flag to prevent taking a
screenshots

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SubhamTyagi/loco-answers/issues/415?email_source=notifications&email_token=ALPWASI4TDO2GU7EQOC4SCLQCEQHFA5CNFSM4IHPSB4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GEJEQ#issuecomment-516703378>,
or mute the thread

**Comment by shibapradhan** [comment]
Bro me job get answer ko click karta hoon tabhi e app autometically hide ho
jata he or ese hi interface aata he...
  App crashed...

**Comment by shibapradhan** [comment]
Plz help me bro....

**Comment by shibapradhan** [comment]
Bro plz me ...bot is not work
