### ISSUE TITLE
Ocr not working on Android 10

### ISSUE THREAD

**Issue by Jayanthbm** [SubhamTyagi/loco-answers#426]
**App Crashing when i click start OCR**

**To Reproduce**
1. Go to 'App'
2. Click on 'Start OCR'
3. Select the profile

**Expected behavior**
App closing

**Smartphone (please complete the following information):**
 - Device: One Plus 6
 - OS: Android 10
 - Version 2.4-chital

**Comment by SubhamTyagi** [comment]
Could you send the all files from Folder '**TriviaHack/errors**'?

**Comment by Jayanthbm** [comment]
the directory doesn't exists on my phone

**Comment by SubhamTyagi** [comment]
@Jayanthbm Have you allowed the storage permission for app?

**Comment by Jayanthbm** [comment]
> @Jayanthbm Have you allowed the storage permission for app?

**Comment by Jayanthbm** [comment]
Yes i allowed storage permission
Interestingly previous version of trivia hack is working fine

**Comment by grasdaggl** [comment]
Hi Subham,

first of all: thank you for the awesome app, it sure helps to beat those quizzes ;)
I have the same problem on Android 10 on my Pixel 2XL. The App now crashes as soon as I click "get Answers". It didn't log an error, but I logged it with logcat and got this error:
```
 Process: ai.loko.hk.ui, PID: 5403
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Intent.clone()' on a null object reference
        at ai.loko.hk.ui.ocr.MediaProjectionHelper.getMediaProjection(MediaProjectionHelper.java:56)
        at ai.loko.hk.ui.ocr.Screenshotter.takeScreenshot(Screenshotter.java:92)
        at ai.loko.hk.ui.services.OCRFloating$2.onClick(OCRFloating.java:181)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

i hope this helps :)

kr
Michael
