### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by shibapradhan** [SubhamTyagi/loco-answers#435]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Intent.clone()' on a null object reference
	at ai.loko.hk.ui.ocr.MediaProjectionHelper.getMediaProjection(MediaProjectionHelper.java:56)
	at ai.loko.hk.ui.ocr.Screenshotter.takeScreenshot(Screenshotter.java:74)
	at ai.loko.hk.ui.services.OCRFloating$2.onClick(OCRFloating.java:194)
	at android.view.View.performClick(View.java:5212)
	at android.view.View$PerformClick.run(View.java:21214)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
-----------------

Device Information

APP.VERSION : 32
LAUNCHER.APP : com.bbk.launcher2
TIMEZONE : Asia/Calcutta
VERSION.RELEASE : 6.0.1
VERSION.INCREMENTAL : eng.compiler.20190306.175921
VERSION.SDK.NUMBER : 23
BRAND : vivo
CPU_ABI : armeabi-v7a
CPU_ABI2 : armeabi
MANUFACTURER : vivo
MODEL : vivo 1603
PRODUCT : 1603

**Comment by shibapradhan** [comment]
I face thie interface in game time

**Comment by shibapradhan** [comment]
Can u help..... What is setting in thia app...
