### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by anurag732** [SubhamTyagi/loco-answers#446]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Intent.clone()' on a null object reference
	at ai.loko.hk.ui.ocr.MediaProjectionHelper.getMediaProjection(MediaProjectionHelper.java:56)
	at ai.loko.hk.ui.ocr.Screenshotter.takeScreenshot(Screenshotter.java:74)
	at ai.loko.hk.ui.services.OCRFloating$2.onClick(OCRFloating.java:194)
	at android.view.View.performClick(View.java:5246)
	at android.widget.TextView.performClick(TextView.java:10565)
	at android.view.View$PerformClick.run(View.java:21200)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6946)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
-----------------

Device Information

APP.VERSION : 32
LAUNCHER.APP : com.sec.android.app.launcher
TIMEZONE : Asia/Kolkata
VERSION.RELEASE : 5.1.1
VERSION.INCREMENTAL : J200GDDU2ARL1
VERSION.SDK.NUMBER : 22
BRAND : samsung
CPU_ABI : armeabi-v7a
CPU_ABI2 : armeabi
MANUFACTURER : samsung
MODEL : SM-J200G
PRODUCT : j2ltedd

**Comment by anurag732** [comment]
Error
